name: Publish to npm

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      publish_npm:
        description: 'Publish to npm'
        required: false
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  npm:
    name: Publish to npm
    if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && inputs.publish_npm)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - run: bun install --frozen-lockfile

      - name: Build JS
        run: bun run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
